-- Copia y pega esto en el SQL Editor de tu Dashboard de Supabase

-- 1. Crear la tabla 'videos'
create table public.videos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  url text not null,
  category text not null,
  subcategory text, -- Nueva columna agregada
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar seguridad (RLS)
alter table public.videos enable row level security;

-- 3. Políticas de acceso (Permisos)

-- Permitir que CUALQUIER persona vea los videos (para la web pública)
create policy "Videos públicos" 
on public.videos for select 
to public 
using (true);

-- Permitir que SOLO usuarios logueados inserten videos
create policy "Admin insertar" 
on public.videos for insert 
to authenticated 
with check (true);

-- Permitir que SOLO usuarios logueados borren videos
create policy "Admin borrar" 
on public.videos for delete 
to authenticated 
using (true);

-- =======================================================
-- NOTA: SI YA CREASTE LA TABLA ANTES, EJECUTA ESTO:
-- alter table public.videos add column subcategory text;
-- =======================================================

